###############################################################################
# Data module - RDS PostgreSQL (Multi-AZ) with credentials in Secrets Manager.
#   - Master password is generated by Terraform (never hardcoded).
#   - Stored as a JSON secret the app reads at boot via its instance role.
#   - Multi-AZ toggle: keep false for cheap demos, true to prove HA/failover.
###############################################################################

resource "random_password" "db" {
  length  = 20
  special = false # avoid characters that complicate connection strings
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-db-subnets"
  subnet_ids = var.data_subnet_ids
  tags       = { Name = "${var.name}-db-subnets" }
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name}-db"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage # storage autoscaling
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result
  port     = var.db_port

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.rds_sg_id]
  multi_az               = var.multi_az
  publicly_accessible    = false

  backup_retention_period    = var.backup_retention_days
  backup_window              = "03:00-04:00"
  maintenance_window         = "Mon:04:00-Mon:05:00"
  auto_minor_version_upgrade = true
  deletion_protection        = var.deletion_protection

  # For a portfolio, skip the final snapshot so `destroy` is clean/free.
  skip_final_snapshot = var.skip_final_snapshot

  performance_insights_enabled = var.performance_insights
  apply_immediately            = true

  tags = { Name = "${var.name}-db" }
}

# ---------- Secrets Manager: connection details the app reads at boot ----------
resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name}/db/credentials"
  description             = "FortifyStack RDS credentials + endpoint"
  recovery_window_in_days = 0 # allow immediate delete on teardown (portfolio)
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.this.address
    port     = var.db_port
    dbname   = var.db_name
    engine   = "postgres"
  })
}
